#!/bin/bash

function updatePatch() {
    local var=$1
    local url=$2
    new_sha256=`yq -r '.[] | select(.url|endswith("'$url'")) .sha256' mozc-deps.yaml`
    sed -i "s|\(+$var = \).*|\1\"$new_sha256\"|g" zip-code.patch
}

updatePatch SHA256_ZIP_CODE_KEN_ALL "https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/ken_all.zip"
updatePatch SHA256_ZIP_CODE_JIGYOSYO "https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip"
