#!/bin/bash

BASE=$PWD
pushd .
if [ ! -d mozc ]; then
    git clone --depth 1 https://github.com/fcitx/mozc/
fi

cd mozc/src/
git fetch --all --prune --filter=tree:0
git checkout origin/fcitx
git submodule update --init

set -e

rm -rf $HOME/.cache/bazel

_MOZC_BAZEL_CACHE=$TMPDIR/mozc_cache

rm -rf $_MOZC_BAZEL_CACHE
for target in unix/fcitx5:fcitx5-mozc.so server:mozc_server gui/tool:mozc_tool; do
    # Only cquery accepts --config and it can also trigger the cache update
    flatpak run --share=network --filesystem=host --runtime=org.kde.Sdk//6.6 --command=sh --env=PKG_CONFIG_PATH=/app/lib/pkgconfig org.fcitx.Fcitx5 -c "/usr/lib/sdk/bazel/bin/bazel cquery --repository_cache="$_MOZC_BAZEL_CACHE" --config oss_linux $target"
done

pushd .
cd $_MOZC_BAZEL_CACHE
for f in `find -name 'id*'` ; do
    echo "- type: file"
    echo -n "  url: "
    awk '{print $1}' $f
    echo "  dest: bazel-deps"
    sha=`dirname $f`
    sha=`basename $sha`
    echo "  sha256: $sha"
done > $BASE/mozc-deps.yaml
popd

yq -y -i 'sort_by(.url)' $BASE/mozc-deps.yaml

rm -rf $_MOZC_BAZEL_CACHE

popd
$BASE/update_mozc_zip_code_patch
