name: Check for updates
on:
  schedule: # for scheduling to work this file must be in the default branch
    - cron: "13 * * * *"
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: archlinux:latest
      options: --init --privileged
    strategy:
      fail-fast: false

    steps:
      - name: Setup
        run: |
          pacman -Syu --needed --noconfirm flatpak git
          flatpak install -y --system --from https://dl.flathub.org/repo/appstream/org.flathub.flatpak-external-data-checker.flatpakref

      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Update
        run: |
          for f in org.fcitx.Fcitx5*.yaml; do
            flatpak run --filesystem=$PWD org.flathub.flatpak-external-data-checker --update --edit-only $f
          done
          git diff || true

      - name: Create Pull request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            *.yaml
          commit-message: |
            Update dependencies
            - Updated ${{ github.event.repository.updated_at}}
          branch: external-deps
          delete-branch: true
          title: 'Update dependencies'
          body: |
            - Updated ${{ github.event.repository.updated_at}}

