name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 13 * * *"

jobs:
  update:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo apt-utils wget unzip
          sudo apt-get install -y git curl unzip jq flatpak pipx
          pipx install yq
      - name: Generate flatpak info Hash
        id: flatpak-hash
        run: |
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          packages="org.fcitx.Fcitx5/x86_64/stable org.kde.Sdk/x86_64/6.6 org.freedesktop.Sdk/x86_64/23.08 org.freedesktop.Sdk/aarch64/23.08"
          HASH_SEEDS=$(for p in $packages; do LC_ALL=C flatpak remote-info --user flathub $p; done)

          HASH=$(echo -e "$HASH_SEEDS" |sha256sum -|cut -f1 -d" ")
          echo -e "$HASH_SEEDS"
          echo $HASH
          echo "FLATPAK_HASH=${HASH}" >> $GITHUB_OUTPUT

      - name: Cache Flatpak
        uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/flatpak/
          key: ${{ runner.os }}-flatpak-${{ steps.flatpak-hash.outputs.FLATPAK_HASH }}
          restore-keys: |
            ${{ runner.os }}-flatpak-${{ steps.flatpak-hash.outputs.FLATPAK_HASH }}

      - name: Install Sdk and Runtime of Flatpak(x86_64)
        run: |
          flatpak install --user -y flathub org.fcitx.Fcitx5/x86_64/stable org.kde.Sdk/x86_64/6.6 org.freedesktop.Sdk/x86_64/23.08
          flatpak update -y

      - name: Install Sdk and Runtime of Flatpak(aarch64)
        run: |
          flatpak install --user -y flathub org.freedesktop.Sdk/aarch64/23.08
          flatpak update -y

      - name: Qemu and binfmt(aarch64 emultation)
        run: |
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo systemctl restart systemd-binfmt.service
          systemctl status systemd-binfmt.service
          sudo update-binfmts --enable qemu-aarch64

      - uses: actions/checkout@v4
        with:
          path: flatpak-fcitx5
          submodules: true
      - name: Update
        run: |
          cd flatpak-fcitx5
          # unset ANDROID_NDK_HOME
          env $(printenv | grep '^ANDROID_NDK' | sed 's/=.*//;s/^/-u /') TMPDIR=$PWD/tmp sh -c \
              './update_mozc_deps'
          git diff
          #sudo chown -R root:root .
