name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 13 * * *"

jobs:
  update:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --init --privileged
    strategy:
      fail-fast: false
    steps:
      - name: Setup User
        run: |
          useradd -m builduser
      - name: Install dependencies
        run: |
          pacman -Syu --needed --noconfirm base-devel clang cmake ninja extra-cmake-modules fmt libuv boost git qt6-base qt6-wayland libxkbcommon qt6-webengine flatpak procps-ng python3 yq wget git qemu-user-static-binfmt #aarch64-linux-gnu-glibc
          flatpak install -y --system org.freedesktop.Sdk/aarch64/23.08
      - name: Qemu and binfmt
        run: |
          if [ ! -d /proc/sys/fs/binfmt_misc ]; then
            if ! /sbin/modprobe binfmt_misc ; then
              exit 1
            fi
          fi
          if [ ! -f /proc/sys/fs/binfmt_misc/register ]; then
            if ! mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc ; then
              exit 1
            fi
          fi
          if [ -w "/proc/sys/fs/binfmt_misc/register" ]; then
            sudo sh -c 'echo -1 > /proc/sys/fs/binfmt_misc/qemu-aarch64' || true
            cat /usr/lib/binfmt.d/qemu-aarch64-static.conf|sudo tee /proc/sys/fs/binfmt_misc/register || true
          fi

      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5
          path: fcitx5
      - name: Cache fcitx5 data files
        uses: actions/cache@v4
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt') }}
      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off -DENABLE_X11=Off -DENABLE_WAYLAND=Off -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off -DENABLE_SERVER=Off -DENABLE_EMOJI=Off -DUSE_SYSTEMD=Off
          install-prefix: /usr
      - uses: actions/checkout@v4
        with:
          path: flatpak-fcitx5
          submodules: true
      - name: Update
        run: |
          cd flatpak-fcitx5
          chown -R builduser:builduser .
          sudo -u builduser \
            LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib64 \
            QEMU_LD_PREFIX=/usr/aarch64-linux-gnu \
            TMPDIR=$PWD/tmp \
            ./update_mozc_deps
          sudo -u builduser ./update_mozc_zip_code_patch
          chown -R root:root .
          git diff || true
